# Generated by Django 5.1.3 on 2024-11-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_mealplan_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mealplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meals.mealplan'),
        ),
    ]
