# Generated by Django 5.1.3 on 2024-11-29 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_comment_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='ingredients',
            field=models.TextField(default=django.utils.timezone.now, help_text='List the ingredients of the recipe separated by commas.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='steps',
            field=models.TextField(default=django.utils.timezone.now, help_text='List the preparation steps of the recipe.'),
            preserve_default=False,
        ),
    ]
