# Generated by Django 5.1.3 on 2024-12-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_mealplan_ingredients_mealplan_steps'),
        ('users', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='meals.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_mealplans', to='users.profile')),
            ],
        ),
    ]
