# Generated by Django 5.1.3 on 2024-12-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_savedmeals'),
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedmeals',
            unique_together={('user', 'mealplan')},
        ),
    ]
