# Generated by Django 5.1.3 on 2024-12-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_savedmeals_unique_together'),
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedmeals',
            name='mealplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.mealplan'),
        ),
        migrations.AlterField(
            model_name='savedmeals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
