# Generated by Django 5.1.3 on 2024-12-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_savedmeals_mealplan_alter_savedmeals_user'),
        ('users', '0002_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedmeals',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='savedmeals',
            name='mealplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='meals.mealplan'),
        ),
        migrations.AlterField(
            model_name='savedmeals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to='users.profile'),
        ),
    ]
